name: Maven CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
    - name: Bump version
      uses: 'mickem/gh-action-bump-maven-version'
      with:
        commit-message: '[CI/CD] Bump the version'
    - name: Build project with Maven
      run: mvn -B package --file pom.xml
